### ISSUE TITLE
Use a meaningful title in the Usage-Based Discovery pages

### ISSUE THREAD

**Issue by clynnes** [ESIPFed/ubd-tool-remotedb#16]
Right now, it just says "Home" in the current pages. This is not very descriptive, and especially hard to recognize in histories, bookmark bars, etc.

At the very least, the title should say "Usage-Based Discovery" on each page, but it might be even better if it were qualified by where in the application you are, such as "Usage-Based Discovery - Application Topics" and 'Usage-Based Discovery - Applications".

**Comment by parthdarji55** [comment]
using 'Usage Based Discovery' as the title of many pages with the | <route base> add on to identify which page your on
