### ISSUE TITLE
Application bug, double category names

### ISSUE THREAD

**Issue by parthdarji55** [ESIPFed/ubd-tool-remotedb#22]
# Bug
There are duplicate categories
# To Reproduce
1. Go to the application 
2. and you can see the two flood categories, two water categories, and two cyclone categories
# Expected behavior
removed duplicates

**Comment by sxia1** [comment]
caused by duplicate application topics in the database like "Floods" VS "Floods "

**Comment by parthdarji55** [comment]
caused by differences in the CSV where 2 topic names would be very similar and sometimes differed by a space
